apiVersion: v1
kind: Service
metadata:
  namespace: netsil
  name: netsil
spec:
  selector:
    app: netsil
    component: netsil
  ports:
    - name: https
      port: 443
      nodePort: 30443
    - name: port2001
      port: 2001
    - name: port2003
      port: 2003
    - name: port2003udp
      port: 2003
      protocol: UDP
    - name: port5000
      port: 5000
    - name: port8888
      port: 8888
      nodePort: 30088
  type: NodePort 
