apiVersion: v1
kind: ReplicationController
metadata:
  namespace: netsil
  name: netsil-lite
spec:
  replicas: 1
  selector:
    app: netsil
    component: netsil-lite
  template:
    metadata:
      name: stream-processor
      labels:
        app: netsil
        component: netsil-lite
        version: stable
    spec:
      containers:
      - name: netsil-lite
        image: netsil/netsil-lite:stable-0.2.29
        command:
        - /tini
        - -g
        - --
        - /root/start.sh
        - run
        - netsil-lite
        securityContext:
          privileged: true
        env:
        - name: PRODUCT_FLAVOR
          value: Lite
        - name: DEPLOY_ENV
          value: docker-compose
        - name: NODEJS_ENV
          value: NODE_ENV=production
        - name: BUILD_ENV
          value: production
        - name: VALID_INDEX_NAMES
          value: events,notifications
        - name: NETSIL_BUILD_BRANCH
          value: stable
        - name: NETSIL_VERSION_NUMBER
          value: 0.2.29
        ports:
        - containerPort: 443
        - containerPort: 2001
        - containerPort: 2003
        - containerPort: 2003
          protocol: UDP
        volumeMounts:
        - name: root
          mountPath: /outer_host
        - name: log
          mountPath: /var/log/netsil
        - name: var-tmp
          mountPath: /var/tmp
      volumes:
      - name: root
        hostPath:
          path: /
      - name: log
        hostPath:
          path: /var/log/netsil
      - name: var-tmp
        hostPath:
          path: /var/tmp
