apiVersion: v1
kind: ReplicationController
metadata:
  namespace: netsil
  name: netsil-lite
spec:
  replicas: 1
  selector:
    app: netsil
    component: netsil-lite
  template:
    metadata:
      name: stream-processor
      labels:
        app: netsil
        component: netsil-lite
        version: stable
    spec:
      containers:
      - name: netsil-lite
        image: netsil/netsil-lite:stable-1.0.0
        command:
        - /root/startup.sh
        securityContext:
          privileged: true
        env:
        - name: PRODUCT_FLAVOR
          value: Lite
        - name: DEPLOY_ENV
          value: docker-compose
        - name: NODEJS_ENV
          value: NODE_ENV=production
        - name: BUILD_ENV
          value: production
        - name: VALID_INDEX_NAMES
          value: event,notification
        - name: NETSIL_BUILD_BRANCH
          value: stable
        - name: NETSIL_VERSION_NUMBER
          value: 0.2.33
        ports:
        - containerPort: 443
        - containerPort: 2001
        - containerPort: 2003
        - containerPort: 2003
          protocol: UDP
        volumeMounts:
        - name: root
          mountPath: /outer_host
        - name: log
          mountPath: /var/log/netsil
        - name: var-tmp
          mountPath: /var/tmp
        - name: redis
          mountPath: /var/lib/redis
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
        - name: alerts
          mountPath: /opt/netsil/alerts/data
        - name: user-persistence
          mountPath: /opt/netsil/user-persistence/data
      volumes:
      - name: root
        hostPath:
          path: /
      - name: log
        hostPath:
          path: /var/log/netsil
      - name: var-tmp
        hostPath:
          path: /var/tmp
      - name: redis
        hostPath:
          path: /opt/netsil/lite/redis
      - name: elasticsearch
        hostPath:
          path: /opt/netsil/lite/elasticsearch/data
      - name: alerts
        hostPath:
          path: /opt/netsil/lite/alerts/data
      - name: user-persistence
        hostPath:
          path: /opt/netsil/lite/user-persistence/data
