apiVersion: v1
kind: Service
metadata:
  namespace: netsil
  name: netsil-lite
spec:
  selector:
    app: netsil
    component: netsil-lite
  ports:
    - name: https
      port: 443
      nodePort: 30443
    - name: port2001
      port: 2001
    - name: port2003
      port: 2003
    - name: port2003udp
      port: 2003
      protocol: UDP
  type: NodePort